import { AdminBar } from "@/components/AdminBar"
import { cn } from "@/lib/utils"
import { Providers } from "@/providers"
import { InitTheme } from "@/providers/Theme/InitTheme"
import { Vazirmatn } from "next/font/google"
import '../(app)/globals.css'

const vazir = Vazirmatn({
  subsets: ['arabic'],
  weight: ['300', '400', '500', '700'],
  variable: '--font-vazir',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={cn('h-full', vazir.className)} lang="fa" dir="rtl" suppressHydrationWarning>
          <head>
            <InitTheme />
            <link href="/favicon.ico" rel="icon" sizes="32x32" />
            <link href="/favicon.svg" rel="icon" type="image/svg+xml" />
          </head>
          <body className="font-vazir">
            <Providers>
              <AdminBar />    
              <main>{children}</main>
            </Providers>
          </body>
        </html>
  )
}
